
shell = "/usr/bin/zsh"
live_config_reload=true

[font]
normal.family="JetBrainsMonoNL Nerd Font Mono"
normal.style="Semibold"
size=16

[window]
dimensions = { columns = 80, lines = 25}
decorations = "Full"
opacity = 0.9
startup_mode = "Windowed"
dynamic_title = true